### ISSUE TITLE
Updated version request

### ISSUE THREAD

**Issue by ericjenott** [staberas/M5Paper-Visual-Novel-Engine#1]
Hello, and thanks for making this great visual novel engine!  I see in your twitter posts that you have developed a lot of features which haven't been pushed to this repository yet.  Would you be willing to push them up or share them?  I am doing some fairly serious development on M5Paper, working on building a full-featured e-reader.  Currently working on a keyboard that allows me to type at full speed.  Besides that, I would like to try my hand at creating some content for your visual novel engine, and perhaps it will give me some inspiration for features to add to my e-reader program.  Thank you!

**Comment by staberas** [comment]
Hi, my intent is to see if there is any interest in using my engine since it takes time to cleanup and documenting it and id rather work on new features.  Currently the feature i added is choice selection, which can load new chapters(files) or skip pages(skip pages within a file/chapter) . I will push this one in a few days since you asked

**Comment by ericjenott** [comment]
Thank you！
